<?
header('Content-Type: application/json');
include "../db.php";

$id = (int) $_POST['id'];

$stmt = $db->prepare("SELECT * FROM `t_COMMUNIQUE` WHERE `PK_COMMUNIQUE`=?");
$stmt->execute([$id]);
$result = $stmt->fetch(PDO::FETCH_ASSOC);

echo json_encode([
    'result' => $result
]);


INSERT INTO `t_tst_transaction`(`TST_ID_BENEFICIARY`, `TST_MOTIF_PAIEMENT`, `TST_PK_TRANSACTION`, `TST_AMOUNT`, `TST_HPT_HOSPITAL`, `TST_FML_FORMULA`, `TST_GRT_EMAIL`, `TST_CURRENCY`, `TST_STATUS`, `TST_NUMBER_MONTH`, `TST_CODE_SPR`, `TST_CODE_TRANSAC_LISUNGI`, `TST_FULLNAME_BUYER`, `TST_PAYER_ID`, `TST_TOTAL_AMOUNT`, `TST_PAYER_ADRESS`) VALUES (`P_ID_BENEFICIARY`,`P_MOTIF_PAIEMENT`,`P_PK_TRANSACTION`,`P_AMOUNT`,`P_HPT_HOSPITAL`,`P_FML_FORMULA`,`P_GRT_EMAIL`,`P_CURRENCY`,`P_STATUS`,`P_NUMBER_MONTH`,`P_CODE_SPR`,`P_CODE_TRANSAC_LISUNGI`,`P_FULLNAME_BUYER`,`P_PAYER_ID`,`P_TOTAL_AMOUNT`,`P_PAYER_ADRESS)